require("mini.ai").setup()
require("mini.basics").setup()
require("mini.tabline").setup()
require("mini.trailspace").setup()
require("mini.cursorword").setup()
-- require("mini.completion").setup()
require("mini.comment").setup()
-- require("mini.burfremove").setup()
require("mini.pairs").setup()
require("mini.notify").setup()
