# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/130dcf15-bbd0-4b13-a60b-03b5ffab8eb7";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd" "noatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1260-70E3";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/130dcf15-bbd0-4b13-a60b-03b5ffab8eb7";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress=zstd" "noatime" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/130dcf15-bbd0-4b13-a60b-03b5ffab8eb7";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd" "noatime" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/130dcf15-bbd0-4b13-a60b-03b5ffab8eb7";
      fsType = "btrfs";
      options = [ "subvol=@logs" "compress=zstd" "noatime" ];
    };

  fileSystems."/home/dymdym/storage" =
    { device = "/dev/disk/by-uuid/64c0aa61-f925-4c36-b846-b414af70f2f3";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd" "noatime" ];
    };

  fileSystems."/home/dymdym/storage/data" =
    { device = "/dev/disk/by-uuid/64c0aa61-f925-4c36-b846-b414af70f2f3";
      fsType = "btrfs";
      options = [ "subvol=data" "compress=zstd" "noatime" ];
    };

  fileSystems."/home/dymdym/storage/games" =
    { device = "/dev/disk/by-uuid/64c0aa61-f925-4c36-b846-b414af70f2f3";
      fsType = "btrfs";
      options = [ "subvol=games" "compress=zstd" "noatime" ];
    };

  fileSystems."/home/dymdym/storage/important" =
    { device = "/dev/disk/by-uuid/64c0aa61-f925-4c36-b846-b414af70f2f3";
      fsType = "btrfs";
      options = [ "subvol=important" "compress=zstd" "noatime" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
